export const ROUTES = {
  QUESTIONS: [
    { name: 'Popular', url: '/' },
    { name: 'Recent', url: '/' },
    { name: 'Following', url: '/' },
    { name: 'Saved', url: '/' },
    { name: 'User Defined', url: '/' },
  ],
  MOCK_QUESTIONS: [
    {
      url: '/question/1',
      votes: 2,
      answers: 1,
      views: 27,
      title: 'How should tall fesque be cut before winter?',
      tags: ['grass', 'tall fesque', 'winter prep'],
      tld: 'https://www.google.com',
      emailAddress: 'jay@google.com',
    },
    {
      url: '/question/2',
      votes: 7,
      answers: 1,
      views: 80,
      title: 'Should yellow pine neddles be removed?',
      tags: ['Pine', 'conifer', 'trimming'],
      tld: 'https://www.google.com',
      emailAddress: 'jay@google.com',
    },
    {
      url: '/question/3',
      votes: 3,
      answers: 1,
      views: 21,
      title: 'Is mulch harmful to bed soil?',
      tags: ['mulch', 'soil', 'plant bed'],
      tld: 'https://www.google.com',
      emailAddress: 'jay@google.com',
    },
    {
      url: '/question/4',
      votes: 7,
      answers: 1,
      views: 43,
      title: 'What is the annual growth rate of a red maple?',
      tags: ['deciduous', 'red maple', 'lithuania'],
      tld: 'https://www.google.com',
      emailAddress: 'jay@google.com',
    },
  ],
}
